config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'os_controls/:os', to: 'os_controls#show', as: 'os_controls'
  post 'os_controls/generate', to: 'os_controls#generate', as: 'generate_controls'
  # get 'os_controls/show'
  # get 'os_controls/generate'
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @operating_systems = ['RedHat Enterprise Linux 8', 'RedHat Enterprise Linux 7', 'Alma Linux 8', 'Alma Linux 7', 
      'Oracle Linux 8', 'Oracle Linux 7', 'CentOS 8', 'CentOS 7', 'Ubuntu 20']
  end
end

app/controllers/os_controls_controller.rb
require 'yaml'
require_relative '../jobs/generate_heira'

# rest of the code
# require 'pry'

class OsControlsController < ApplicationController
  def show
    @os = params[:os]
    @controls = get_controls(@os)
    @mapping_data = read_mapping_data.first[1].first[1].first[1]
  end

  def generate
    @os = params[:os]
    @selected_controls = params[:controls] || []
    @option = params[:option]
    final_controls_to_show = get_final_controls(@selected_controls, @option)

    @yaml_content = GenerateHeiraData.new.content('cis', 'server', '2', @option, @selected_controls, load_required_hash(final_controls_to_show), 'dummy/path', '', @os)

    respond_to do |format|
      format.html { render :generate }
      format.yaml { send_data @yaml_content, filename: "#{@os}_controls.yml", type: 'application/x-yaml', disposition: 'attachment' }
    end
  end

  private

  def get_controls(os)
    controls = {
      'RedHat Enterprise Linux 8' => pick_controls_only,
      'RedHat Enterprise Linux 7' => pick_controls_only,
      'Alma Linux 8' => pick_controls_only,
      'Alma Linux 7' => pick_controls_only,
      'Oracle Linux 8' => pick_controls_only,
      'Oracle Linux 7' => pick_controls_only,
      'CentOS 8' => pick_controls_only,
      'CentOS 7' => pick_controls_only,
      'Ubuntu 20' => pick_controls_only
    }
    controls[os] || []
  end

  def read_mapping_data
    @mapping_data ||= YAML.load_file(Rails.root.join('config', 'controls.yml'))
  end

  def read_resource_data
    @resource_data ||= YAML.load_file(Rails.root.join('config', 'resource_data.yml'))
  end

  def pick_controls_only
    removed_controls = %w[sce_options]
    read_resource_data.map { |_klass, details| details['controls'].keys }.flatten.map(&:to_s).reject { |control| removed_controls.include?(control)  }
  end

  def get_final_controls(selected_controls, selected_option)
    if %w[all only].include?(selected_option)
      selected_controls
    elsif selected_option.eql?('ignore')
      pick_controls_only - selected_controls
    else
      []
    end
  end

  def load_required_hash(final_controls)
    filtered_data = {}
    read_resource_data.each do |class_name, class_data|
      class_data['controls'].each do |control_name, control_data|
        if final_controls.include?(control_name)
          next if control_data.eql?('no_params')

          control_data_hash = {}
          control_data.each do |k, v|
            control_data_hash[k] = v
          end
          filtered_data[control_name] = control_data_hash
        end
      end
    end

    filtered_data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/os_controls_helper.rb
module OsControlsHelper
end

app/views/home/index.html.erb
<% content_for :content_title do %>
  <h1>Select Operating System</h1>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Operating Systems</th>
      <th></th> <!-- Empty header for the link -->
    </tr>
  </thead>
  <tbody>
    <% @operating_systems.each do |os| %>
      <tr>
        <td><%= os %></td>
        <td><%= link_to 'Select', os_controls_path(os), class: 'btn btn-info' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>HieraFileGenerator</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/default.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>

  <!-- and it's easy to individually load additional languages -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/go.min.js"></script>

  <script>hljs.highlightAll();</script>

  <style>
    .logo {
      width: 300px; /* Adjust the size as needed */
      height: auto;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="d-flex justify-content-between align-items-center my-3">
      <h1 class="display-4">Hiera File Generator</h1>
      <%= image_tag 'puppet-logo.jpg', alt: 'Puppet Logo', class: 'logo' %>
    </div>
    <div class="content">
      <p>Introducing our Hiera File Generator tool, designed to streamline the process of creating Hiera files effortlessly.</p>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/os_controls/generate.html.erb
  <div class="row">
    <div class="col">
      <h3 class="display-5">Generated Hiera for <%= @os %></h3>
      <div class="mt-1 position-relative">
        <div class="d-flex justify-content-end">
          <button type="button" class="btn btn-secondary btn-sm mr-2" id="copy-button">Copy to clipboard</button>    
          <%= form_with url: generate_controls_path(os: @os, controls: @selected_controls, option: @option, format: :yaml), method: :post, local: true do |form| %>
            <%= form.submit 'Download Hiera File', class: 'btn btn-info btn-sm' %>
          <% end %>  
        </div>
        <pre style="height: 550px">
          <code id="yaml-content">
            <%= @yaml_content %>
          </code>
        </pre>
      </div>
    </div>
  </div>
  
  <script>
    document.addEventListener('DOMContentLoaded', (event) => {
      hljs.highlightAll();
    });

    document.getElementById('copy-button').addEventListener('click', function() {
      var textarea = document.getElementById('yaml-content');
      var text = textarea.innerText;
      navigator.clipboard.writeText(text)
        .then(function() {
          console.log('Text copied to clipboard');
          var tooltip = document.getElementById('tooltip-text');
          tooltip.innerText = 'Copied to clipboard';
        })
        .catch(function(error) {
          console.error('Failed to copy text to clipboard:', error);
        });
    });

    document.getElementById('copy-button').addEventListener('mouseover', function() {
      var tooltip = document.getElementById('tooltip-text');
      tooltip.innerText = 'Copy to clipboard';
    });
  </script>

app/views/os_controls/show.html.erb
<% content_for :content_title do %>
  <h1>Controls Available for <%= @os %> OS</h1>
<% end %>

<div>
  <%= form_with url: generate_controls_path, method: :post, local: true, data: { turbo: false }, id: 'controls-form' do %>
    <input type="hidden" name="os" value="<%= @os %>">
    <input type="hidden" name="format" value="html">

    <table class="table table-borderless">
      <thead>
        <tr>
          <th colspan='3' class="table-info">Benchmark Configuration Option</th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td>
                <%= radio_button_tag 'option', 'only', true, id: 'option_only' %>
                <%= label_tag 'option_only', 'Only Selected Controls' %>
            </td>
            <td>
                <%= radio_button_tag 'option', 'ignore', false, id: 'option_ignore' %>
                <%= label_tag 'option_ignore', 'Ignore Selected Controls' %>
            </td>
            <td>
              <%= radio_button_tag 'option', 'all', false, id: 'option_all' %>
              <%= label_tag 'option_all', 'Add All Controls' %>
            </td>
          </tr>
      </tbody>
    </table>

    <table class="table table-striped table-hover">
      <thead>
        <tr class="table-info">
          <th><%= check_box_tag '', false, id: 'option_all_chk' %> Select</th>
          <script>
            
          </script>
          <th>Control Id</th>
          <th>Control Name</th>
        </tr>
      </thead>
      <tbody>
        <% @controls.each do |control| %>
          <tr>
            <td><%= check_box_tag 'controls[]', control, false, class: 'control-checkbox' %></td>
            <td><%= label_tag "controls_#{control}", "#{@mapping_data[control.to_s][0]}" %></td>
            <td><%= label_tag "controls_#{control}", "#{@mapping_data[control.to_s][1]}" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="text-center">
      <%= submit_tag 'Generate Hiera File', class: 'btn btn-info submit-btn' %>
    </div>
  <% end %>
</div>

<script>

  let option_all_chk = document.getElementById('option_all_chk');
  option_all_chk.addEventListener('change', function(e) {
    let checkboxes = document.querySelectorAll('.control-checkbox');
    checkboxes.forEach(checkbox => checkbox.checked = option_all_chk.checked);
  });

  let option_all = document.getElementById('option_all');
  option_all.addEventListener('change', function(e) {
    document.querySelectorAll('.control-checkbox').forEach(checkbox => checkbox.checked = true)
  });
</script>